### ISSUE TITLE
pysolfc hanghiba

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk1#10]
https://github.com/uhulinux/ub-ubk2/issues/6
https://github.com/uhulinux/ub-ubk1/issues/9

**Comment by attuska** [comment]
A https://github.com/uhulinux/ub-ubk1/commit/1043b8cc3d2e64b4d347d16f8395e6b3a0dcea3e nem oldotta meg.

**Comment by attuska** [comment]
Valami a 32 bites telepítményen, vagy a 32 bites csomagokban nem jó, mert ubk1/64 biten szép a pysolfc, semmi hiba nem mutatkozik.

**Comment by attuska** [comment]
A https://github.com/uhulinux/ub-ubk1/commit/37bdbf566814727746bb8f3ff731e8ea8c57b59b sem javított UBK1/32 biten.
UBK1/64 biten ellenben jó továbbra is.

**Comment by attuska** [comment]
A régi ubk1/32 bites telepítményemen ellenben meglepetésemre jó a grafika, csak hang nincs.
A pysol-sound-server fel van telepítve.

> attila@localhost:~$ pysol
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pysollib/pysolaudio.py", line 183, in startServer
    import pysolsoundserver
ImportError: No module named 'pysolsoundserver'
attila@localhost:~$

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk1/commit/f86fe1e9432d38a7040cef740045a2ab58ad173a
Visszaállva kevert python2 és python3 -ra van hangja.

**Comment by rezso** [comment]
Én meg megcsináltam a pysol-sound-servert python3-ra, úgyhogy megint nem lesz jó.

**Comment by attuska** [comment]
> attila@localhost:~$ pysol
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pysollib/pysolaudio.py", line 183, in startServer
    import pysolsoundserver
ImportError: /usr/lib/python3.5/site-packages/pysolsoundserver.cpython-35m-i386-linux-gnu.so: undefined symbol: Py_InitModule4
attila@localhost:~$

**Comment by rezso** [comment]
Szuper. Új pysolfc és ósdi (2004-es) pysol-sound-server, ami persze a python C API változásokról sem tud. Szeretem az ilyen fejlesztőket.
Szóval egyelőre marad python2-es.
