### ISSUE TITLE
shift+alt+del key combination not working (sddm, dwm, i3)

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk1#13]
dwm
Mintha a shift hatástalan lenne, nem lehet belőle kilépni, sem st terminált nyitni.

kilépés: alt+shift+q
terminál: alt+shift+enter

A dmenu megy, meg minden más az alt+egybillentyű -vel.
Az alt+space is működik. Az egér két szeme is.

Természetesen ubk2 -n is ugyanígy (nem)működik.

**Comment by attuska** [comment]
Megcsináltam az i3 -at, ott sem működnek a Shift módosítók. Ott Alt+Shift+e a kilépés alapértelmezett kombinációja, ez nem működik. Átírva a ~.config/i3/config fájlát Alt+q -ra már működik.

> # exit i3 (logs you out of your X session)
#$mod+Shift+e 
bindsym $mod+q exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"


Az X billenyű kezelésben valahol hiba van!

**Comment by attuska** [comment]
https://i3wm.org/docs/userguide.html#_default_keybindings

Még a Ctrl+Alt+Del sem működik dwm, i3, és sddm alatt!
Gnome3, Icewm, Mate, fluxbox alatt él a Ctrl+Alt+Del!
Valami nagyon nem jó az alap grafikus billentyű észlelésnél.

**Comment by attuska** [comment]
A shift+alt le van foglalva a billetyűzet kiosztás váltására.

> attila@localhost:/usr/src/UHUBUILD/ubk2-64mirror$ zgrep 01-keyboard Contents.gz
x.org-input-keyboard:   0   0  f  644      207 /etc/X11/xorg.conf.d/01-keyboard-layout.conf
attila@localhost:/usr/src/UHUBUILD/ubk2-64mirror$ 

A 01-keyboard-layout fájl addonsból lett adva és most így néz ki:

> Section "InputClass"
        Identifier             "keyboard-layout"
        MatchIsKeyboard        "on"
        Option "XkbLayout"     "hu"
        Option "XkbOptions"    "grp:alt_shift_toggle"
EndSection

Az   **Option "XkbOptions"    "grp:alt_shift_toggle"** sor kitörlése után szépen működik a dwm.
alt+shift+q ->kilép
alt+shift+enter -> st terminál nyílik.

Az i3 is működne.

Mire kellne ezt a "grp:alt_shift_toogle -t megváltoztatni?
Kell ez a sor egyáltalán?

**Comment by rezso** [comment]
A grp:alt_shift_toggle arra van, hogy az Alt+Shift kombinációkkal lehet billentyűzetkiosztást váltani.
Szerintem nem nagyon fog hiányozni, ha kiveszed, de inkább csak kommentezd ki egyelőre.

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk1/commit/ae5945a7ea2211482acb890af7957c73796db324
A jobb Ctrl és jobb Shift lett a váltó, azzal lehet billentyűzetkiosztást váltani.
A dwm már működik így, használhatja már az akinek az kell. Az i3 is hasonló billentyű kombinációkkal működik, mint a dwm. Az awesome nem is roszz, annyira nem elvetemült, mint az előbbi kettő.
