### ISSUE TITLE
bashstyle-ng nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk1#8]
https://github.com/uhulinux/ub-ubk2/issues/26

Itt meg:

> attila@localhost:/usr/lib/wikidpad$ bashstyle
>
>BashStyle-NG Version 9.3 starting
Lockfile does not exist
ResetConfig: no up-to-date backup or vendor configuration found, using factory defaults.
LoadConfig: no vendor configuration found, using factory defaults.
CheckConfig: User configuration up-to-date.
FixUpConfig: checking for outdated values.
Traceback (most recent call last):
  File "/usr/share/bashstyle-ng/ui/bs-ng.py", line 339, in <module>
    hwg = BashStyleNG()
  File "/usr/share/bashstyle-ng/ui/bs-ng.py", line 333, in __init__
    suui.InitStartupUI()
  File "/usr/share/bashstyle-ng/ui/configui.py", line 123, in InitStartupUI
    if config.CheckBashStyle() == False:
  File "/usr/share/bashstyle-ng/ui/config.py", line 207, in CheckBashStyle
    rc = open(os.path.expanduser("~/.bashrc"), "r")
FileNotFoundError: [Errno 2] Nincs ilyen fájl vagy könyvtár: '/home/attila/.bashrc'
attila@localhost:/usr/lib/wikidpad$

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk1/commit/64f84173f117870fe3224834e98ecab11b793fce

**Comment by rezso** [comment]
A gond amúgy az, hogy session induláskor is van szerepe a bashrc-nek. Konkrétan a profile hivatkozik rá. Szóval ez így bezavarhat.
Inkább azt kellene megoldani, hogy ha nincs ~/.bashrc, akkor az /etc/bashrc-t olvassa.
